version: '3.8'

services:
  trading_bot:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: trading_bot
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
    volumes:
      - ../logs:/app/logs
      - ../data:/app/data
      - ../models:/app/models
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - trading_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

  redis:
    image: redis:6.2-alpine
    container_name: trading_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trading_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  monitoring:
    build:
      context: ..
      dockerfile: deployment/monitoring.Dockerfile
    container_name: trading_monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"  # Prometheus
      - "3000:3000"  # Grafana
    volumes:
      - ../monitoring:/etc/monitoring
      - monitoring_data:/var/lib/monitoring
    depends_on:
      - trading_bot
    networks:
      - trading_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

networks:
  trading_network:
    driver: bridge

volumes:
  redis_data:
  monitoring_data: 