env:
  initial_balance: 10000.0
  trading_fee: 0.001
  window_size: 20
  normalize: true
  stack_size: 4
  max_position_size: 1.0

data:
  exchange: "binance"
  symbols: ["BTC/USDT"]
  timeframe: "1h"
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  cache_dir: "data/raw"

model:
  fcnet_hiddens: [64, 64]
  lr: 0.001
  gamma: 0.99
  epsilon: 0.2

training:
  total_timesteps: 10000
  early_stop: 20
  batch_size: 64

paths:
  model_dir: "models"
  data_dir: "data"
  log_dir: "logs"
