data:
  exchange: binance
  qlib:
    features:
    - name: RSI
      window: 14
    - fast: 12
      name: MACD
      signal: 9
      slow: 26
    - dev: 2.0
      name: BB
      window: 20
    provider_uri: data/qlib_data
  start_date: '2023-01-01'
  symbols:
  - BTC/USDT
  timeframe: 1d
env:
  initial_balance: 10000.0
  max_position_size: 1.0
  normalize: true
  stack_size: 4
  trading_fee: 0.001
  window_size: 30
model:
  clip_param: 0.2
  entropy_coeff: 0.01
  fcnet_activation: tanh
  fcnet_hiddens:
  - 256
  - 256
  framework: torch
  grad_clip: null
  hidden_size: 256
  kl_coeff: 0.2
  lambda: 0.95
  lr: 0.0001
  lr_schedule: null
  name: PPO
  num_layers: 2
  num_sgd_iter: 30
  optimizer: adam
  sgd_minibatch_size: 128
  train_batch_size: 4000
  use_gae: true
  vf_clip_param: 10.0
  vf_loss_coeff: 1.0
training:
  checkpoint_at_end: true
  checkpoint_freq: 10
  evaluation_duration: 10
  evaluation_interval: 10
  evaluation_num_episodes: 10
  framework: torch
  log_level: INFO
  num_envs_per_worker: 1
  num_workers: 4
  rollout_fragment_length: 200
  total_timesteps: 1000000
  train_batch_size: 4000
