version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/trading_bot.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf-8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

loggers:
  trading_bot:
    level: INFO
    handlers: [console, file, error_file]
    propagate: false

  trading_bot.env:
    level: INFO
    handlers: [console, file]
    propagate: false

  trading_bot.agent:
    level: INFO
    handlers: [console, file]
    propagate: false

  trading_bot.data:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file] 