data:
  end_date: '2023-01-07'
  exchange: binance
  start_date: '2023-01-01'
  symbols:
  - BTC/USDT
  timeframe: 1h
env:
  initial_balance: 10000
  trading_fee: 0.001
  window_size: 10
experiment_name: test_training
model:
  fcnet_hiddens:
  - 32
  lr: 0.001
training:
  checkpoint_freq: 10
  early_stop: 20
  total_timesteps: 50
