name: Deploy to Hyak

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH to Hyak and deploy
      run: |
        ssh ${{ secrets.HYAK_USER }}@klone.hyak.uw.edu <<EOF
        cd /path/to/project
        git pull
        sbatch scripts/run_hyak_job.sh
        EOF

